name: Delete Stale PRs and Branches
on:
  push:
    branches:
      - main     
  schedule:
    - cron: "* * * * *"  # Runs every day at midnight UTC
jobs:
  delete-stale-prs-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          branch: main
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Run Python script
        env:
          GITHUB_TOKEN: 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
        run: |
          python .github/workflows/scripts/dpe_stale_pr_clean.py


          